### ISSUE TITLE
Allow user to configure which stock is displayed

### ISSUE THREAD

**Issue by matthew-d-jones** [TTitcombe/Casset#49]
As a user, I want to be able to choose which stock Casset displays information about.

Acceptance criteria:
* The gui should contain an editable toolbar into which a user can enter a stock symbol (e.g. "AAPL" for Apple)
* When the stock button is clicked, recent information about the stock is displayed on the gui. This should include:
    - The stock symbol for which the information relates
    - The date of the information
    - The close price
* The user-entered symbols should be case-insensitive. E.g. "aapl" and "AAPL" should both return information on Apple
* A clear message should displayed if the stock symbol cannot be found
* A clear message should be displayed if GET requests cannot be made
* Users should be able to continue using the application after successful *and* unsuccessful requests for information

Points: 3

**Comment by TTitcombe** [comment]
Closed in #55
